# This file is auto-generated by 3_preprocessing.py
blocklist = {'the': 'the', '!': '!', 's': 's', 'n': 'n', 'wa': 'was'}
whitelist = ['branzino', 'carozza', 'confit', 'congee', 'cozy', 'dal', 'facie', 'favorite', 'fixe', 'flavoring', 'foie', 'frites', 'gras', 'grazie', 'gulab', 'jamun', 'kha', 'maitre', 'medicore', 'mizu', 'mom', 'msg', 'neighborhood', 'noir', 'nyc', 'overpack', 'porcini', 'prima', 'prixe', 'russe', 'shabu', 'svc', 'tartare', 'theater', 'tristate', 'uncourteous', 'volare', 'wks']
